title: Parcel Forwarding Poland
description: A simple and elegant theme for Jekyll and GitHub Pages.
social_link: twitter
social_username: parcel Poland
github_repo: athena
github_username: Parcel Poland
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /parcel Poland
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
